language: python
python:
  - "2.7"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - unixodbc-dev
install: 
  - pip install -r requirements.txt
  - pip install coverage
script: nosetests --nologcapture -v -s --with-coverage --cover-erase --cover-package=changeme tests/*.py
