language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc
    - g++
    - unixodbc-dev
install: 
  - pip install -r requirements.txt
  - pip install coverage
services:
  - redis-server
script: nosetests --nologcapture -v -s --with-coverage --cover-erase --cover-package=changeme tests/*.py
